### ISSUE TITLE
Passing --f to scan writes shell prompt to output file

### ISSUE THREAD

**Issue by connoryates** [nishgowda/docktor#1]
This is probably not the intended outcome:

```
$ ./bin/docktor scan --i nginx --f nginx.out
$ cat nginx.out
Docker Scan relies upon access to Snyk, a third party provider, do you consent to proceed using Snyk? (y/N)
```

**Comment by nishgowda** [comment]
The command uses Snyk to scan for vulnerabilities so I think you have to enable that first in order for it to work first. Should have documented that first my bad!

**Comment by nishgowda** [comment]
Updated the documentation to include this and also added testing to check for it as well when the command is executed.
