### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by lacerdanycolas** [nishgowda/docktor#3]
After executing the command 'make build', log returns 

`/usr/local/go/src/github.com/nishgowda/docktor/lib/healthcheck/healthcheck.go:11:2: cannot find package "github.com/docker/docker/api/types/container" in any of:
	/usr/local/go/src/vendor/github.com/docker/docker/api/types/container (vendor tree)
	/usr/local/go/src/github.com/docker/docker/api/types/container (from $GOROOT)
	/home/nlo/go/src/github.com/docker/docker/api/types/container (from $GOPATH)
/usr/local/go/src/github.com/nishgowda/docktor/lib/healthcheck/healthcheck.go:12:2: cannot find package "github.com/docker/docker/api/types/filters" in any of:
	/usr/local/go/src/vendor/github.com/docker/docker/api/types/filters (vendor tree)
	/usr/local/go/src/github.com/docker/docker/api/types/filters (from $GOROOT)
	/home/nlo/go/src/github.com/docker/docker/api/types/filters (from $GOPATH)
../../docker/docker/registry/registry.go:23:2: cannot find package "github.com/docker/docker/autogen/dockerversion" in any of:
	/home/nlo/go/src/github.com/docker/docker/vendor/github.com/docker/docker/autogen/dockerversion (vendor tree)
	/usr/local/go/src/github.com/docker/docker/autogen/dockerversion (from $GOROOT)
	/home/nlo/go/src/github.com/docker/docker/autogen/dockerversion (from $GOPATH)
/usr/local/go/src/github.com/nishgowda/docktor/lib/heal/heal.go:13:2: cannot find package "github.com/docker/docker/client" in any of:
	/usr/local/go/src/vendor/github.com/docker/docker/client (vendor tree)
	/usr/local/go/src/github.com/docker/docker/client (from $GOROOT)
	/home/nlo/go/src/github.com/docker/docker/client (from $GOPATH)
/usr/local/go/src/github.com/nishgowda/docktor/lib/healthcheck/healthcheck.go:14:2: cannot find package "github.com/docker/go-connections/nat" in any of:
	/usr/local/go/src/vendor/github.com/docker/go-connections/nat (vendor tree)
	/usr/local/go/src/github.com/docker/go-connections/nat (from $GOROOT)
	/home/nlo/go/src/github.com/docker/go-connections/nat (from $GOPATH)
/usr/local/go/src/github.com/nishgowda/docktor/bin/cmd/root.go:6:2: cannot find package "github.com/mitchellh/go-homedir" in any of:
	/usr/local/go/src/vendor/github.com/mitchellh/go-homedir (vendor tree)
	/usr/local/go/src/github.com/mitchellh/go-homedir (from $GOROOT)
	/home/nlo/go/src/github.com/mitchellh/go-homedir (from $GOPATH)
/usr/local/go/src/github.com/nishgowda/docktor/bin/cmd/autoheal.go:7:2: cannot find package "github.com/spf13/cobra" in any of:
	/usr/local/go/src/vendor/github.com/spf13/cobra (vendor tree)
	/usr/local/go/src/github.com/spf13/cobra (from $GOROOT)
	/home/nlo/go/src/github.com/spf13/cobra (from $GOPATH)
/usr/local/go/src/github.com/nishgowda/docktor/bin/cmd/root.go:8:2: cannot find package "github.com/spf13/viper" in any of:
	/usr/local/go/src/vendor/github.com/spf13/viper (vendor tree)
	/usr/local/go/src/github.com/spf13/viper (from $GOROOT)
	/home/nlo/go/src/github.com/spf13/viper (from $GOPATH)
Makefile:9: recipe for target 'build' failed
make: [build] Error 1 (ignored)
`

What to do to fix?

**Comment by nishgowda** [comment]
I think this may be an issue with the go version you're using see https://github.com/kubernetes-sigs/kubebuilder/issues/786 I think it's a similar problem. Probably updating your go version or doing what that says should fix it.

**Comment by lacerdanycolas** [comment]
Updated version for 1.6, and it's running! Thanks
